version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: taxscanner-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: taxscanner
      POSTGRES_USER: taxscanner
      POSTGRES_PASSWORD: ${DB_PASSWORD:-changeme123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/prisma/migrations:/docker-entrypoint-initdb.d
    networks:
      - taxscanner-network
    ports:
      - "5432:5432"

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taxscanner-backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      NODE_ENV: production
      PORT: 3001
      DATABASE_URL: postgresql://taxscanner:${DB_PASSWORD:-changeme123}@postgres:5432/taxscanner
      GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
      CORS_ORIGIN: ${FRONTEND_URL:-http://localhost:3000}
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    networks:
      - taxscanner-network
    ports:
      - "3001:3001"

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taxscanner-frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: ${BACKEND_URL:-http://localhost:3001}
      NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${GOOGLE_MAPS_API_KEY}
    networks:
      - taxscanner-network
    ports:
      - "3000:3000"

networks:
  taxscanner-network:
    driver: bridge

volumes:
  postgres_data: 